### ISSUE TITLE
Ask for miniImageNet params.json

### ISSUE THREAD

**Issue by zjy526223908** [jik0730/MAML-in-pytorch#1]
Thanks for your excellent reproduction. I wonder if you could provide a miniImageNet experiment params json file. Thank you very much.

**Comment by jik0730** [comment]
Hello:) Thanks for your interest on my reproduction code.
The only change you need to modify on params.json for miniImageNet experiments is to change "Omniglot" to "ImageNet" in "dataset" field. After that you should use miniImageNet dataset for training the model.
