### ISSUE TITLE
link dataset with the code

### ISSUE THREAD

**Issue by sudarshan1994** [jik0730/MAML-in-pytorch#2]
hey I am trying to run the model on MiniImageNet, do I just have to point the code the location of downloaded dataset ? is any preprocessing required ?

**Comment by jik0730** [comment]
Hi, thanks for your interest on my code.
If you have downloaded miniImageNet dataset, all you need to do for the experiment is to point the directory of your downloaded dataset in the argument as --data_dir DIR_PATH in train.py file.
If you want faster experiment with miniImageNet, you may want to pre-resize the dataset or other preprocessing procedures. This may alleviate bottleneck in CPU when training, where main job for CPU is to preprocess original image fed into the model such as resizing.
