### ISSUE TITLE
How to  organize the Omniglot and MiniImagent datasets

### ISSUE THREAD

**Issue by vikasverma1077** [jik0730/MAML-in-pytorch#3]
Can you provide instructions on how to organize the datasets such that it can be used in your code?

**Comment by jik0730** [comment]
Hi, thanks for your interest on my code.
I followed organization of datasets for experiments used in https://github.com/renmengye/few-shot-ssl-public.
In the repository I linked, there are links to download the datasets including Omniglot and MiniImageNet. You can use those for our experiments after unzipping.
